### ISSUE TITLE
Struggling to get the phylogenetic tree using case study 1

### ISSUE THREAD

**Issue by juandeburgos** [drboothtj/getphylo#1]
Hello! I was just trying getphylo on your sample data and I'm struggling to get the actual phylogenetic tree file. When I run the program I have the feedback  I attach down here and I do get some output archives (fasta, tsv, dmnd) , but not the tree file or the aligned fasta. I checked that I had downloaded fasttree2, muscle and diamond. Any clue what could be wrong? 

(getphylo) ubulinux@hcuv-covid:~/Escritorio/HDD/Analysis-in-use/getphylo_test$ getphylo -g 'case_study_1/*.gb'
[11:48:52] INFO      : Running getphylo version 0.1.0.
Traceback (most recent call last):
  File "/home/ubulinux/.local/bin/getphylo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/__main__.py", line 13, in entrypoint
    main.main()
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/main.py", line 105, in main
    align.make_alignments(checkpoint, output, final_loci, gbks, args.cpus)
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/align.py", line 209, in make_alignments
    do_alignments(output, cpus)
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/align.py", line 83, in do_alignments
    io.run_in_parallel(muscle.run_muscle, args_list, cpus) #add cpu arg
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/utils/io.py", line 146, in run_in_parallel
    return_value = [function(*args) for args in args_list]
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/utils/io.py", line 146, in <listcomp>
    return_value = [function(*args) for args in args_list]
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/ext/muscle.py", line 23, in run_muscle
    io.run_in_command_line(command)
  File "/home/ubulinux/.local/lib/python3.10/site-packages/getphylo/utils/io.py", line 132, in run_in_command_line
    raise RuntimeError('Failed to run: ' + str(command))
RuntimeError: Failed to run: ['muscle', '-in', '/home/ubulinux/Escritorio/HDD/Analysis-in-use/getphylo_test/output/unaligned_fasta/NZ_CP025533_1_CYL77_RS08125.fasta', '-out', '/home/ubulinux/Escritorio/HDD/Analysis-in-use/getphylo_test/output/aligned_fasta/NZ_CP025533_1_CYL77_RS08125.fasta']

**Comment by drboothtj** [comment]
Hi,

Thanks for raising the issue. Currently, getphylo only supports MUSCLE versions <5. This is because MUSCLE changed its parser after this version.

I suspect this will be causing the error. Can you confirm the MUSCLE version?

I will also add in version detection and a work around as soon as possible.

**Comment by juandeburgos** [comment]
Hi, 
I did have MUSCLE 5. I tried it with a previous version and it worked perfectly.
Thank you for the help

**Comment by drboothtj** [comment]
Great! Thank you for your feedback!
