### ISSUE TITLE
Issue with paths containing spaces

### ISSUE THREAD

**Issue by Sam-Will** [drboothtj/getphylo#3]
Issue when working with onedrive and localpath

```
(getphylo) saedwi@NNFCB-L1095:~/onedrive/01_NNF/02_Glycopeptide/01_Genomics/get_phylo$ getphylo -g 'Update_110924/*.gbk' -o output_110924 -t 'protein_id'
[13:49:33] INFO      : Running getphylo version 0.2.1.
Traceback (most recent call last):
  File "/home/saedwi/.local/bin/getphylo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/__main__.py", line 13, in entrypoint
    main.main()
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/main.py", line 72, in main
    extract.extract_data(
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/extract.py", line 147, in extract_data
    build_diamond_databases(output, cpus, diamond_location)
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/extract.py", line 43, in build_diamond_databases
    io.run_in_parallel(diamond.make_diamond_database, args_list, cpus)
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/utils/io.py", line 156, in run_in_parallel
    return_value = [function(*args) for args in args_list]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/utils/io.py", line 156, in <listcomp>
    return_value = [function(*args) for args in args_list]
                    ^^^^^^^^^^^^^^^
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/ext/diamond.py", line 28, in make_diamond_database
    io.run_in_command_line(command)
  File "/home/saedwi/.local/lib/python3.11/site-packages/getphylo/utils/io.py", line 136, in run_in_command_line
    raise RuntimeError('Failed to run: ' + str(command))
RuntimeError: Failed to run: ['diamond', 'makedb', '--db', '/mnt/c/Users/saedwi/OneDrive', '-', 'Danmarks', 'Tekniske', 'Universitet/01_NNF/02_Glycopeptide/01_Genomics/get_phylo/output_110924/dmnd/A40926.dmnd', '--in', '/mnt/c/Users/saedwi/OneDrive', '-', 'Danmarks', 'Tekniske', 'Universitet/01_NNF/02_Glycopeptide/01_Genomics/get_phylo/output_110924/fasta/A40926.fasta']
```

**Comment by drboothtj** [comment]
All fixed. Let me know if there are any more problems @Sam-Will. I also add the blastp parameters we talked about.

@SJShaw I used a slightly different method that I felt was safer. Instead of the split on the space, I made it so the run_in_command_line function only accepts a list of arguments. That way, the file name is never split on spaces. I think this is much safer!
